
BLENDER="C:\Program Files\Blender Foundation\Blender 2.90\blender.exe"
DIST=../dist

all : \
    $(DIST)/arena.pnct \
    $(DIST)/arena.scene \

$(DIST)/arena.scene : arena.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "arena.blend:Main" "$(DIST)/arena.scene"

$(DIST)/arena.pnct : arena.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "arena.blend:Main" "$(DIST)/arena.pnct" 
